services:
  - type: web
    name: langgraph-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

  - type: web
    name: n8n-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile

databases:
  - name: n8n-db
    plan: free
    ipAllowList: ["0.0.0.0/0"]
